"use strict";
let estChovendo = false;
estChovendo = true;
let idade = 37;
const nacionalidade = 'Brasileiro';
const colegas = ['lucas', 'fernanda'];
const tecnologias = ['html', 'css'];
const notas = [7, 8, 9];
const lista = ['luiz', true, 25];
let idadeDaAna = 24;
idadeDaAna = "25 anos";
let dadosDaApi;
dadosDaApi = 10;
dadosDaApi = true;
dadosDaApi = [1, 2, 3];
dadosDaApi = 'string';
